/*
-- Query: SELECT * FROM heroku_f52866be0c962a0.user
LIMIT 0, 1000

-- Date: 2022-10-03 14:03
*/
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (4,'Amanda','Nunes','anunes@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Computer Scientist',100000,'3242 Lyon Avenue','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (14,'Alexander','Volkanovski','avolkanovski@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Computer Scientist',80000,'4341 Harter Street','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (24,'Khabib','Nurmagomedov','knurmagomedov@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','CEO',62000,'1692 Red Maple Drive','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (34,'Kamaru','Usman','kusman@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Marketing Administrator',72000,'3148 Goosetown Drive','false');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (44,'Israel','Adesanya','iadesanya@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Database Developer',199000,'2191 Rogers Street','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (54,'Henry','Cejudo','hcejudo@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Export Manager',120000,'808 Gambler Lane','false');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (64,'Valentina','Shevchenko','vshevchenko@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Software Applications Engineer',90000,'459 Winding Way','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (74,'Tyron','Woodley','twoodley@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Sales Director',80000,'2164 May Street','false');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (84,'Rose','Namajunas ','rnamajunas@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Intranet Developer',120000,'4770 Apple Lane','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (94,'Tony','Ferguson ','tferguson@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Sales Director',50000,'2270 Rainy Day Drive','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (104,'Jorge','Masvidal ','jmasvidal@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','District Sales Manager',45000,'2128 Stonecoal Road','false');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (114,'Nate','Diaz ','ndiaz@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Computer Scientist',190000,'1104 Saint James Drive','false');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (124,'Conor','McGregor ','cmcGregor@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Chief Technology Officer',20000,'855 Sycamore Lake Road','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (134,'Cris','Cyborg ','ccyborg@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','VP Marketing',80000,'3170 Granville Lane','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (144,'Tecia','Torres ','ttorres@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Chief Technology Officer',62000,'1501 Dola Mine Road','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (154,'Ronda','Rousey ','rrousey@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Database Developer',100000,'4999 Hidden Meadow Drive','false');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (164,'Holly','Holm ','hholm@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Marketing Director',50000,'1761 Cedar Street','true');
INSERT INTO `user` (`id`,`first_name`,`last_name`,`email`,`phone`,`comments`,`status`,`position`,`salary`,`address`,`paid`) VALUES (174,'Joanna','Jedrzejczyk ','jjedrzejczyk@ufc.com','012345 678910','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','active','Intranet Developer',100000,'749 Barrington Court','true');
